# Generated by Django 5.0.7 on 2024-08-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('creat_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
